# Numpy Workshop

[documentation](https://numpy.org/doc/)

In [231]:
import numpy as np
import matplotlib.pyplot as plt

In [232]:
np.float32(23)

23.0

In [280]:
np.random.seed(10)
np.random.randint(0, 10, (2, 3))
np.random.randint(0, 9, (2, 3))

array([[1, 8, 0],
       [8, 6, 4]])

In [287]:
x = np.array([''], dtype=bool)
x

array([False])

# Indexing

In [341]:
x = np.random.randint(0, 100, (4, 4))
x

array([[62, 42, 34, 40],
       [46, 32, 94, 86],
       [58, 69, 45, 18],
       [50, 44,  1, 63]])

In [345]:
mask = (x % 3 == 0)
y = x[mask]

array([42, 69, 45, 18, 63])

In [347]:
y[0] = 0
x

array([[62, 42, 34, 40],
       [46, 32, 94, 86],
       [58, 69, 45, 18],
       [50, 44,  1, 63]])

In [323]:
y = x[:5, :2]
y[0, 0] = 0

In [339]:
arr_i = []
for index, val in np.ndenumerate(x):
    if val % 3 == 0:
        arr_i.append(index)
            
print(arr_i)

[(0, 3), (1, 3)]


In [348]:
size = 10**2
x = np.random.randint(0, 100, (size, size))

In [349]:
%%timeit
mask = (x % 3 == 0)
y = x[mask]

173 µs ± 6.32 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [350]:
%%timeit
arr = []
for index, val in np.ndenumerate(x):
    if val % 3 == 0:
        arr_i.append(val)

9.4 ms ± 330 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [365]:
x = np.random.randint(0, 100, (10, 10))

In [359]:
y = [(1, 2, 10, 7), (1, 2, 0, 9)]

In [363]:
x[np.where(x % 3 == 0)]

array([63, 72, 24, ..., 78, 51, 96])

In [398]:
y = x[x % 6 == 0]
y

array([96, 48, 90, 90, 90, 90, 54,  0, 24, 84, 84, 48])

In [400]:
z = y.reshape((3, 4))

In [401]:
z.flatten()

array([96, 48, 90, 90, 90, 90, 54,  0, 24, 84, 84, 48])

In [409]:
x = np.random.randint(0, 5, (1000, 10))

In [403]:
x

array([[2, 2, 2, 2, 4],
       [0, 3, 4, 1, 4],
       [1, 4, 1, 3, 4],
       [1, 4, 3, 3, 3],
       [2, 0, 3, 4, 3],
       [3, 0, 4, 0, 3],
       [3, 4, 2, 2, 1],
       [0, 1, 1, 2, 4],
       [2, 2, 4, 4, 4],
       [3, 1, 1, 3, 2]])

In [430]:
round(5.654, 2)

5.65

In [440]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [439]:
y = np.array([[10], [20], [30]])
y

array([[10],
       [20],
       [30]])

In [443]:
y

array([[-2. ],
       [-1.9],
       [-1.8],
       [-1.7],
       [-1.6],
       [-1.5],
       [-1.4],
       [-1.3],
       [-1.2],
       [-1.1],
       [-1. ],
       [-0.9],
       [-0.8],
       [-0.7],
       [-0.6],
       [-0.5],
       [-0.4],
       [-0.3],
       [-0.2],
       [-0.1],
       [ 0. ],
       [ 0.1],
       [ 0.2],
       [ 0.3],
       [ 0.4],
       [ 0.5],
       [ 0.6],
       [ 0.7],
       [ 0.8],
       [ 0.9],
       [ 1. ],
       [ 1.1],
       [ 1.2],
       [ 1.3],
       [ 1.4],
       [ 1.5],
       [ 1.6],
       [ 1.7],
       [ 1.8],
       [ 1.9]])

In [444]:
x

array([[-4. , -3.9, -3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. ,
        -2.9, -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. , -1.9,
        -1.8, -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9, -0.8,
        -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,
         0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,
         1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,
         2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,
         3.7,  3.8,  3.9]])

In [449]:
y, x = np.ogrid[-2:2:0.5, -4:4:0.5]
points = x + 1j * y

In [450]:
points**2 + (0.8 * 1j)

array([[12.  +16.8j,  8.25+14.8j,  5.  +12.8j,  2.25+10.8j,  0.   +8.8j,
        -1.75 +6.8j, -3.   +4.8j, -3.75 +2.8j, -4.   +0.8j, -3.75 -1.2j,
        -3.   -3.2j, -1.75 -5.2j,  0.   -7.2j,  2.25 -9.2j,  5.  -11.2j,
         8.25-13.2j],
       [13.75+12.8j, 10.  +11.3j,  6.75 +9.8j,  4.   +8.3j,  1.75 +6.8j,
         0.   +5.3j, -1.25 +3.8j, -2.   +2.3j, -2.25 +0.8j, -2.   -0.7j,
        -1.25 -2.2j,  0.   -3.7j,  1.75 -5.2j,  4.   -6.7j,  6.75 -8.2j,
        10.   -9.7j],
       [15.   +8.8j, 11.25 +7.8j,  8.   +6.8j,  5.25 +5.8j,  3.   +4.8j,
         1.25 +3.8j,  0.   +2.8j, -0.75 +1.8j, -1.   +0.8j, -0.75 -0.2j,
         0.   -1.2j,  1.25 -2.2j,  3.   -3.2j,  5.25 -4.2j,  8.   -5.2j,
        11.25 -6.2j],
       [15.75 +4.8j, 12.   +4.3j,  8.75 +3.8j,  6.   +3.3j,  3.75 +2.8j,
         2.   +2.3j,  0.75 +1.8j,  0.   +1.3j, -0.25 +0.8j,  0.   +0.3j,
         0.75 -0.2j,  2.   -0.7j,  3.75 -1.2j,  6.   -1.7j,  8.75 -2.2j,
        12.   -2.7j],
       [16.   +0.8j, 12.25 +0.8j,  9

In [ ]:
x 